// <auto-generated />
using System;
using Airline.UserRegister.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Airline.UserRegister.Migrations
{
    [DbContext(typeof(UserRegisterDbContext))]
    [Migration("20220502135051_mySecondUserRegistaion")]
    partial class mySecondUserRegistaion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Airline.UserRegister.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.ToTable("UserRegistor");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Address = "BASAR",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2022, 5, 2, 19, 20, 51, 62, DateTimeKind.Local).AddTicks(5249),
                            DateOfBirth = new DateTime(2022, 5, 2, 19, 20, 51, 61, DateTimeKind.Local).AddTicks(4754),
                            Email = "kakumani@gmail.com",
                            FirstName = "NAGARAJU",
                            LastName = "KAKUMANI",
                            Password = "Pass@word",
                            UpdatedDate = new DateTime(2022, 5, 2, 19, 20, 51, 62, DateTimeKind.Local).AddTicks(5678),
                            Updatedby = "Admin",
                            mobile = "9666491876"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
